import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_JS = ROOT / "www" / "js" / "data.js"
OUT_JS = ROOT / "www" / "js" / "pitch-data.js"
SOURCE_URL = "https://raw.githubusercontent.com/mifunetoshiro/kanjium/master/data/source_files/raw/accents.txt"


def load_words():
    text = DATA_JS.read_text(encoding="utf-8")
    m = re.search(r"window\.GENKI_DATA\s*=\s*(\{.*\});?\s*$", text, re.S)
    if not m:
        raise RuntimeError("Не найден window.GENKI_DATA в www/js/data.js")
    data = json.loads(m.group(1))
    return data.get("words") or data.get("vocab") or []


def main():
    words = load_words()
    wanted = set()
    for w in words:
      j = (w.get("j") or w.get("k") or "").strip()
      k = (w.get("k") or "").strip()
      if j and k:
          wanted.add((j, k))
          wanted.add((k, k))

    found = {}
    with urllib.request.urlopen(SOURCE_URL, timeout=60) as resp:
        for raw in resp.read().decode("utf-8", "replace").splitlines():
            parts = raw.split("\t")
            if len(parts) != 3:
                continue
            word, kana, accents = [p.strip() for p in parts]
            if (word, kana) not in wanted and (kana, kana) not in wanted:
                continue
            vals = [int(x) for x in accents.split(",") if x.isdigit()]
            if not vals:
                continue
            found[f"{word}|{kana}"] = vals
            found.setdefault(f"{kana}|{kana}", vals)

    body = json.dumps(found, ensure_ascii=False, separators=(",", ":"))
    OUT_JS.write_text(
        "// Generated by tools/build_pitch_data.py from Kanjium accents.txt\n"
        f"window.PITCH_DATA = {body};\n",
        encoding="utf-8",
    )
    print(f"Pitch entries: {len(found)}")


if __name__ == "__main__":
    main()
